name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 89.111.163.48
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/lstkmk.ru
          git pull origin main
          npm install
          rm -rf .next
          npm run build
          mkdir -p /var/log/pm2
          pm2 delete lstkmk || true
          pm2 start ecosystem.config.js --env production
          pm2 save
